Repository 51bootcamp/HappyBugs, pull requests merged in 2019-02, with the labels that each got.

#94 Issue#13 52 perpetrators matching
  Backend/models/perpetrator.js
  Backend/models/report.js
  Backend/models/user.js
  Backend/router/v1/report.ctrl.js
Labels: enhancement

#139 Issue #138 Fix SignUp Bugs
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/SignUpActivity.java
Labels: bug, priority:High

#118 issue#50 To limit the number of logins
  Backend/.DS_Store
  Backend/lib/passport.js
  Backend/models/user.js
  Backend/router/.DS_Store
  Backend/router/v1/user.js
  Frontend/app/src/main/AndroidManifest.xml
Labels: enhancement

#162 Issue#147 edit report, bug fixed
  Frontend/app/src/main/java/io/happybugs/happybugs/APIInterface/APIInterface.java
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/MainActivity.java
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java
  Frontend/app/src/main/res/layout/report_listview_item.xml
  Frontend/app/src/main/res/values/strings.xml
Labels: enhancement

#165 Check when perpetrator is null in Create report part
  Backend/models/perpetrator.js
  Backend/router/v1/report.ctrl.js
Labels: bug

#171 Issue#170 fix bugs in reportactivity
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/CloseReportDialog.java
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportActivity.java
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java
  Frontend/app/src/main/res/layout/report_listview_item.xml
Labels: bug, priority:High

#176 Issue#175 XML mismatch hotfix
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java
Labels: bug, priority:High

#183 Issue#182-hotfix
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewAdapter.java
  Frontend/app/src/main/java/io/happybugs/happybugs/activity/ReportListViewItem.java
Labels: bug

#173 Issue#12 email authentication
  Backend/.DS_Store
  Backend/.gitignore
  Backend/HTML/img/logo.png
  Backend/HTML/verified.html
  Backend/HTML/verifiedFail.html
  Backend/app.js
  Backend/config/email_config_template.json
  Backend/lib/passport.js
  Backend/lib/verification/verificationEmail.js
  Backend/models/user.js
  Backend/models/verificationToken.js
  Backend/package-lock.json
  Backend/package.json
  Backend/router/.DS_Store
  Backend/router/v1/user.js
Labels: enhancement
